### ISSUE TITLE
[question] Can tinker9 work without GPU?

### ISSUE THREAD

**Issue by yurivict** [TinkerTools/tinker9#109]
The README isn't clear about this.

There are systems which don't have GPU drivers, for example FreeBSD.

**Comment by zhi-wang** [comment]
Yes. It will require a different set of flags passed to CMake although I don't recommend running it on the CPU platform. The flags are described in https://github.com/TinkerTools/tinker9/blob/master/doc/manual/m/install/buildwithcmake.rst

The code migration is still far from completion therefore a lot of rarely used functionalities are not available in Tinker9 yet. Current CPU implementation is correct but unsurprisingly slow because we haven't started to worry about the OpenMP directives etc., so running longer simulations on the CPU platform is not going to be productive.

Also since the code migration is in progress, Tinker9 still needs the Fortran Tinker (8) static library. For details, please see https://github.com/TinkerTools/tinker9/blob/master/doc/manual/m/install/tinker.rst

These are the two main reasons I don't recommend running Tinker9 on CPU.
