### ISSUE TITLE
Dockerfile script

### ISSUE THREAD

**Issue by BJWiley233** [TinkerTools/tinker9#190]
Hey @zhi-wang , thanks for making the dockerfile script.  The dockerfile that I get from runtime or compile both have `FROM tinkertools/tinker9-devel:cuda10.1-nvhpc20.9` but I am not seeing your tinkertools repo on DockerHub so docker cannot find this image.  

For instance:
```
% docker pull tinkertools/tinker9-devel:cuda10.1-nvhpc20.9
Error response from daemon: pull access denied for tinkertools/tinker9-devel, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by BJWiley233** [comment]
Thanks for the response.  RIS as WashU is still using 10.1 CUDA drivers.  When I run the `tinker9.docker` for runtime using  `./tinker9.docker.py 10.1 runtime` (FYI I had to edit `tinker9.docker` script because `c += "string"` doesn't work if `c` is not initialized in my python3 version) I still get a Dockerfile with tinker devel at top

```
FROM tinkertools/tinker9-devel:cuda10.1-nvhpc20.9 AS tool_image
FROM nvidia/cuda:10.1-runtime-ubuntu18.04
```
I will check out the docker image you posted.  FYI I thought this was nice.  This person's dockerhub repo thanked you!! :) 
https://hub.docker.com/r/xiangzezeng/tinker9.  Do you know them?

**Comment by zhi-wang** [comment]
Yes, Xiangze and I had a lot of discussions. And thanks for reporting the bug in the script.

As for the script you generated, before the `tinkertools` repo is set up on docker hub, you'd (unfortunately) have to build the devel image locally (by `./tinker9.docker 10.1 devel`). This is going to take some time because downloading the compilers will take a while. Let me compile a more recent Tinker9 image and push it to https://hub.docker.com/r/zhiwang/tinker9/tags for now.

**Comment by BJWiley233** [comment]
Thanks :)

**Comment by BJWiley233** [comment]
Hi @zhi-wang,  I tested running dynamic9 on the docker image `zhiwang/tinker9:cuda10.1-20220407` and it works when either I have 1 GPU or if I have more than one and only set `CUDA_VISIBLE_DEVICES` to just 1.  I am assuming that tinker9 might not be able to run on multiple GPUs.  I am running on V100s from RIS at WashU.

**Comment by zhi-wang** [comment]
It should be able to run on a multi-GPU machine. Each calculation can only utilize one GPU though.

**Comment by BJWiley233** [comment]
Do you think a good idea to add print statement before call to `always_check_rt(cudaSetDeviceFlags(cuda_device_flags));` at line [282](https://github.com/TinkerTools/tinker9/blob/cfdfc395a5be6a512b28dc31b6c4d39c90447be7/src/cudart/gpucard.cpp#L282) like you do in function before for "Setting Device ID" something like below between lines 281 and 282 such as:
```
 print(stdout,
      "\n"
      " Setting CUDA Device Flags :  %d\n",
      cuda_device_flags);
```
Or is this redundant?

**Comment by zhi-wang** [comment]
Let me test it on one of our nodes to see if I can have it reappeared. This error message is infamous (to me) -- I could never recreate it. Your report described a new scenario Tinker9 is used and I am interested in what I can find later.

**Comment by zhi-wang** [comment]
This is interesting. The different versions of Cuda runtimes have different behaviors -- the crash doesn't appear in the other docker image with Cuda 11.2. This is probably why I was never able to recreate this issue on our nodes.

I changed the code and pushed the new docker images to https://hub.docker.com/r/tinkertools/tinker9/tags. Please give it a try and let me know if you find any new problems. Thank you.

P.s.
Images on my personal docker hub repo will be removed.

**Comment by BJWiley233** [comment]
Ah yes that will make it much easier for Researchers to fine :) 
I will test and let you know.  Thanks!

**Comment by BJWiley233** [comment]
So I am wondering if this new issue I get is 100% our LSF device setup.  I get it to work on 2 GPUs and 4 GPUs half the time :).  With 2 GPUs if `CUDA_VISIBLE_DEVICES` = `1,2` and with 4 GPUs if `CUDA_VISIBLE_DEVICES` = `1,2,3,0` the new image now works fine without having to do anything special with CUDA-DEVICES.

However every other time with 2 GPUs if `CUDA_VISIBLE_DEVICES` = `2,0` and with 4 GPUs if `CUDA_VISIBLE_DEVICES` = `2,0,3,1` I'll get a funky merge_sort error by from CUDA:
```
 Terminating with uncaught exception :  merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
```

**Comment by zhi-wang** [comment]
Many things can be wrong for you to see this error. This error message was thrown out by a function of the `thrust` library but I don't think this is where the crash happened. Actually, you saw this error message only because there is an explicit check for the error number inside a `thrust` function call. If any bad things happened in other GPU calculations before this checkpoint, you wouldn't see them until this point, and only the last of the accumulated errors would be reported. It's not impossible to check the error code for every CUDA function call or kernel launch, but it won't be practical if we want the best performance.

Not long ago I saw the exact same error message. That was because I failed to allocate a block of GPU memory before it was used. It's hard for me to believe that you have a similar situation here because anything wrong in the code or in the parameters etc. would have similar crashing behavior on the same machine. The situation that only certain GPU cards consistently failed with the same error message makes me speculate that the issue is likely related to the machine setup.

I can't comment on what may go wrong with the machine setup, and I'm a little confused by your commands.
- What is the difference between, for instance, `CUDA_VISIBLE_DEVICES=1,2,3,0` and `CUDA_VISIBLE_DEVICES=2,0,3,1`? Why not `0,1,2,3`?
- As I explained in one of the previous posts, Tinker9 can only utilize one GPU card for a calculation. What is the purpose to set multiple visible devices to the program?
- If you just assign one device number via `CUDA_VISIBLE_DEVICES` for the calculation, I believe you don't need to worry about the `CUDA-DEVICE [INTEGER]` keyword. Are you able to run 4 different jobs on 4 different cards independently on the same node?
- Moreover, if the calculation doesn't take an enormous amount of GPU memory, it is possible to run multiple jobs on the same card? (Speed can be N times slower if the computing chips are fully loaded.) If you see errors here, can you tell what may have forbidden it? If everything still works fine, how is this different than your situation?

**Comment by BJWiley233** [comment]
Ah ok so I thought Tinker might be able to split up the calculations but probably wouldn't make much sense unless you could allocate certain parts of the simulation such as PME calculations and/or non-bonded.  Those orders for `CUDA_VISIBLE_DEVICES` were the defaults when I `bsub` into the GPU blade so didn't realize I could change them/test changing them.  Regardless all the orders work fine now so running them probably around 30 minutes after LSF does their updates at 2:00 AM could have been issue.  Thanks for the Docker image!
