### ISSUE TITLE
Soaking molecule into solvent

### ISSUE THREAD

**Issue by AlexRizk12** [TinkerTools/tinker9#249]
Hello,

I have been using Tinker to execute a molecular dynamics on a DNA molecule. When soaking the molecule into solvent, i obtain a .xyz file with the DNA outside of the box.

I am a bit lost regarding this matter and i would appreciate if you could redirect me towards a tutorial to correctly grasp the use of this tool. Additionally, if you could have any solution to this specific issue.

Thank you in advance !

**Comment by jayponder** [comment]
This is not necessarily "wrong". The convention in the Tinker programs is for periodic simulation boxes to be centered at the global coordinate origin, ie, (0,0,0). Generally, Tinker will move any molecule that strays from the periodic box (ie, where the center of mass of the molecule is no longer inside the central periodic box) back into the box, entering from the opposite face. The most likely thing is that your DNA coordinates are offset from the origin. Then when you solvate the DNA, the water molecules, which are small, will all be moved into the central box. But your DNA may have its center of mass inside the central box while portions stick out of the box. Since periodic boundaries are enforced during an MD simulation, the MD will run correctly- but the trajectory will "look funny" when you observe it in some graphics program.

The usual remedy to this issue is to center your DNA at the origin before "soaking" it. You can do this with the option in the Tinker XYZEDIT program to move the molecule into the inertial frame. This will write a new Tinker XYZ file with the DNA centered, and you can then solvate that centered structure.

**Comment by AlexRizk12** [comment]
Thank you for your valuable help. The DNA molecule was correctly placed at the center of the waterbox.

I would also like to thank you for your explanation as well since it helped me understand the mechanism of use of this tool !
