### ISSUE TITLE
Compiling Tinker9 issues- cannot open/find .mod files

### ISSUE THREAD

**Issue by CallumFrEllis** [TinkerTools/tinker9#251]
Hi TinkerTools Team, 

I have been trying to compile tinker9 on our HPC system at my university for some time, and have managed to get most of the way (I hope) but am hitting some errors which I am struggling with. 

I think git cloning tinker9 does not download the tinker8 linked files which I can do seperately, most things build fine but then when running final.f it cannot find shapes.mod or rotbn.mod (potentially others but it doesnt get that far?) and I cannot find where the .mod files are they are to try and fix it, might someone be able to help please?

I am using gcc/11.1, cuda/12.2, and cmake/3.24.1 on an a100 gpu. Error messages are pasted below, please let me know if you need more info. 

/home/ce3g12/ce3g12/tinker/tinker9/ext/source/final.f:119:10:

  119 |       use rotbn
      |          1
Fatal Error: Cannot open module file 'rotbn.mod' for reading at (1): No such file or directory
compilation terminated.
make[2]: *** [ext/interface/CMakeFiles/tinkerObjF.dir/__/source/final.f.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [ext/interface/CMakeFiles/tinkerObjF.dir/all] Error 2
make: *** [all] Error 2

**Comment by jayponder** [comment]
Hi, The issue is that you are trying to use a version of Tinker8 that is not compatible with Tinker9. I suspect you have downloaded Tinker8 directly from the main GitHub TinkerTools page, and that version is more recent than the version you need to build Tinker9.

Go the the GitHub README file for Tinker9 and follow the instructions there, which will lead you to download and build the correct "canonical" version of Tinker8 that works with the current Tinker9.

**Comment by CallumFrEllis** [comment]
Thank you Jay, this was indeed the case.
